minimum_pre_commit_version: 3.0.0

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.5
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        description: "Prettier is an opinionated code formatter for various languages, including JSON, YAML, Markdown, and more."
        additional_dependencies:
          - prettier@2.8.1

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        description: "Ensures that a file is either empty, or ends with one newline."
      - id: mixed-line-ending
        description: "Replaces or checks mixed line ending."
      - id: trailing-whitespace
        description: "Trims trailing whitespace."
        exclude: '\.md$'
      - id: debug-statements
        description: "Check for debugger imports and py37+ `breakpoint()` calls in Python."
      - id: detect-private-key
        description: "Check for the existence of private keys."
      - id: check-added-large-files
        description: "Check for added large files."

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        description: "Mypy is an optional static type checker for Python."
        args: ["--strict", "--allow-untyped-decorators"]
        exclude: ^(tests|docs)
        additional_dependencies:
          - "types-requests>=2.32.0"

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        description: "Bandit is a tool for finding common security issues in Python code."
        entry: bandit
        language: python
        language_version: python3
        types: [python]
        require_serial: true
        exclude: "tests"

  - repo: https://github.com/jsh9/pydoclint
    rev: 0.4.1
    hooks:
      - id: pydoclint
        args: [--style=google]
